### ISSUE TITLE
Compilation Error on InfoII/Vorlesungen.tex

### ISSUE THREAD

**Issue by erictapen** [FinnIckler/SS15-Skripte#1]
Heyo, ich benutze texliveonfly und bei mir bricht die Kompilierung mit 

! LaTeX Error: File `algorithm2e.sty' not found.

ab. Was hat die Datei algorithm2e.sty zu bedeuten?

Liebe Grüße,
Justin

**Comment by FinnIckler** [comment]
Ich habe algorithmen2e.sty rausgenommen und die eine Verwendung eines algorithm2e Befehls ersetzt.

**Comment by erictapen** [comment]
Danke!
